### 发送消息
POST http://localhost:8091/chat/12345
Content-Type: application/json

{
  "userMessage": "Hello, how are you?"
}

### 获取会话信息
GET http://localhost:8091/chat/12345

### 删除会话
DELETE http://localhost:8091/chat/12345

#翻译
###

GET http://97.64.28.22:50000/gpt-chat-server/chat/test?input=代码写累了，明天周日可以做什么&token=hello
